#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinReference.Droid.Resource", IsApplication=true)]

namespace XamarinReference.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::XamarinReference.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int C1 = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int C10 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int C11 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int C12 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int C13 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int C14 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int C15 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int C16 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int C17 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int C18 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int C19 = 2130968594;
			
			// aapt resource value: 0x7f040001
			public const int C2 = 2130968577;
			
			// aapt resource value: 0x7f040013
			public const int C20 = 2130968595;
			
			// aapt resource value: 0x7f040002
			public const int C3 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int C4 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int C5 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int C6 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int C7 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int C8 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int C9 = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int H1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int H2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int H3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int H4 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int H5 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int H6 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int H7 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int H8 = 2131034119;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appicon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hamburger_menu_white = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int About = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AboutBuild = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AboutDeveloper = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BuildDate = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int BuildOsVersion = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BuildVersion = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int BusinessCardTitle = 2130903047;
			
			// aapt resource value: 0x7f03000a
			public const int Calendar = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Camera = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Cancel = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Confirm = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Delete = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int DeleteFileMessage = 2130903055;
			
			// aapt resource value: 0x7f030008
			public const int DeveloperLogging = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DeveloperOptions = 2130903049;
			
			// aapt resource value: 0x7f030011
			public const int LogFileDelete = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LogFileShare = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int LogFileView = 2130903059;
			
			// aapt resource value: 0x7f030016
			public const int PercentDelivery = 2130903062;
			
			// aapt resource value: 0x7f030014
			public const int PercentPrep = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int PercentWork = 2130903061;
			
			// aapt resource value: 0x7f030019
			public const int TaskForReview = 2130903065;
			
			// aapt resource value: 0x7f030017
			public const int TaskInProgress = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int TaskInReview = 2130903064;
			
			// aapt resource value: 0x7f03001a
			public const int TaskToDo = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Tasks = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ThemeColors = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int ThemeFonts = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int ToDo = 2130903070;
			
			// aapt resource value: 0x7f030020
			public const int TopMovieRentals = 2130903072;
			
			// aapt resource value: 0x7f03001f
			public const int TopMovies = 2130903071;
			
			// aapt resource value: 0x7f030021
			public const int TopMusicVideos = 2130903073;
			
			// aapt resource value: 0x7f030010
			public const int iTunes = 2130903056;
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
